### ISSUE TITLE
Angularjs compatibility?

### ISSUE THREAD

**Issue by haikyuu** [MicrosoftDX/Vorlonjs#19]
It doesn't seem to work with angular, i just added the script tag but in my angular app i get the following error in the console: 
`Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide' is not a valid selector.`

**Comment by deltakosh** [comment]
Are you sure this is linked to vorlon.js? Because I do not see why this happens as we do not touch the DOM

**Comment by niloy** [comment]
Yes, this is definitely vorlon issue. Even I am getting the same errors in my angular application. I started getting those errors only after I included "vorlon.js" script.

**Comment by deltakosh** [comment]
Do you mind sharing your project? Or at least a repro case? I'll fixing asap then:)

**Comment by alexstanbury** [comment]
Same issue here

**Comment by deltakosh** [comment]
Thank you I check it right now :)

**Comment by deltakosh** [comment]
Fixed by https://github.com/MicrosoftDX/Vorlonjs/commit/6550a0eef15e44b78722717db6b3aa54d004bae8

**Comment by SoundLogic** [comment]
thanks for the quick turn-around!

**Comment by alexstanbury** [comment]
I'm still unable to use this in my Angular app, see the screen shot for console errors.

It's also freezing my app when I have the Vorlon script tag commented in.

![screen shot 2015-05-06 at 10 37 18](https://cloud.githubusercontent.com/assets/809537/7490868/0138ef3e-f3dc-11e4-99b8-b617ec8f824b.png)

**Comment by alexstanbury** [comment]
It seems to work ok with the project that I uploaded earlier in the thread though...

**Comment by deltakosh** [comment]
I tried with a couple of angular projects and it was ok
