### ISSUE TITLE
Fix DOM refresh indicator

### ISSUE THREAD

**Issue by meulta** [MicrosoftDX/Vorlonjs#227]
Sometimes the indicator is red but the dom did not changed

**Comment by meulta** [comment]
@csuwildcat Did you have the time to look into this? :)

**Comment by csuwildcat** [comment]
I'm rather busy preparing X-Tag, our Web Components library, for release
this week. I would probably be more free towards the end of the month.

**Comment by lahloumehdi** [comment]
@meulta I think I have fixed the issue. A PR is coming.

**Comment by meulta** [comment]
great thanks, did you already pushed it ? 
I still have the issue on my side :)

**Comment by gleborgne** [comment]
Not yet...

**Comment by meulta** [comment]
No worries I was just checking to know if I could close this :)
