### ISSUE TITLE
Vorlon desktop: ECONNREFUSED 127.0.0.1:1337

### ISSUE THREAD

**Issue by warpdesign** [MicrosoftDX/Vorlonjs#284]
Whenever I run Vorlon desktop, i'm getting a popup with this error.

The first time I ran it, I had this error, right before the windows firewall popup that appear, asking me if I want to accept connection from vorlon.

I accepted, but I'm still getting this error everytime I start the app.

I have nothing that's running on this port. I tried changing the port, without success.

**Comment by meulta** [comment]
Puliing @gleborgne :)

**Comment by alexchen7022** [comment]
I tried to run on win7 64bit environment. System shows the same message and scenario.
By the way. Vorlonjs is really awesome.

**Comment by gleborgne** [comment]
@warpdesign what version of windows are you running ?

Could you try disabling windows firewall before starting the app ?

**Comment by gleborgne** [comment]
If you try starting the vorlon server after app launch, you still have that error ?

**Comment by warpdesign** [comment]
@gleborgne Win 10 (x64). I'll try to disable the firewall and see what happens.

**Comment by alexchen7022** [comment]
Sorry! My test env is Win 10 (x64). And I have disabled the windows firewall, It still show below message.

![image](https://cloud.githubusercontent.com/assets/2408918/11846669/91e0b11a-a454-11e5-81a1-78e6c466a208.png)
![image](https://cloud.githubusercontent.com/assets/2408918/11846246/ba6b33aa-a452-11e5-819d-04ffe6387a64.png)
![image](https://cloud.githubusercontent.com/assets/2408918/11846287/f57ffe94-a452-11e5-9a83-df13a6107ed3.png)

**Comment by warpdesign** [comment]
@alexchen7022 That's exactly the same thing I'm getting.

**Comment by meulta** [comment]
Any ideas @gleborgne  ? :)

**Comment by gleborgne** [comment]
Have you tried changing port in the config screen ? Windows is denying using port 1337

**Comment by alexchen7022** [comment]
Even I change the port. System still show below message.
![image](https://cloud.githubusercontent.com/assets/2408918/11958557/73e5c4c6-a903-11e5-8279-0420cc279798.png)

**Comment by deltakosh** [comment]
Up! @gleborgne did you have time to check this issue?

**Comment by gleborgne** [comment]
Not yet, but I will

**Comment by meulta** [comment]
@alexchen7022 did you manage to find a solution by yourself? :)
Can you give us a status on this ? 
thanks

**Comment by meulta** [comment]
Fixed in latest on dev.

**Comment by mikeburns** [comment]
this issue is still happening for me in 2019 (Win10x64, firewalls deactivated/allowed for all ports, tried multiple different ports, same error message).  When I use the command-line version, I don't get any errors, but the clients never connect when launched from an external device.

Sorry, but I thought this was the very goal of this project, and it looks super promising, and maybe there is something that has happened since 2016, but I'd give everything I have in my pockets for this to work, because I'm sick of having to connect my devices to an actual PC (and in the case of iOS devices, having to go bother my co-worker to let me use their Mac for a while so I can debug some retarded iOS CSS issue)
